### ISSUE TITLE
Login error message after disconnect

### ISSUE THREAD

**Issue by gunslingerfry** [arthepsy/pan-globalprotect-okta#23]
OS: manjaro, uh... 20.0.1 but it's a rolling release so.. current as of today.
openconnect:
```
OpenConnect version v8.05
Using GnuTLS. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp, pulse
```
pan-globalprotect-okta revision: f88beb9d076c3371dc4697cea0ec3b7a85d169d5

When connecting using pan-globalprotect-okta and then ^C to disconnect I get the message:
```
Invalid user name
Logout failed.
Error: argument "via" is wrong: use nexthop syntax to specify multiple via
```
When doing the openconnect connection naively with openconnect:
`echo <pass> | sudo opeconnect --protocol=gp <portal/gateway address> -u <username> --passwd-on-stdin`

I get  `Logout successful` when disconnecting.

**Comment by arthepsy** [comment]
Is this with `execute=1`? Can You try specifying `execute=0` and check that command-line manually? Because, command-line You provided, doesn't come from `pan-globalprotect-okta`, as it supports passing cookies, not passwords.

Othewise, by description, it seems like after You ^C (disconnect), openconnect for some reason asks something and gets passed cookie second time as username. In this case, setting `openconnect_fmt=<cookie>` would help. Care to check that out, also?

**Comment by gunslingerfry** [comment]
@arthepsy yes it is with execute=1. Using execute=0 I still receive the logout failed message. 

I understand the command line I included is not from pan-globalprotect-okta, it was just for reference to see that logout successful is printed in that case. 

`openconnect_fmt=<cookie>` I still receive the message.

**Comment by arthepsy** [comment]
Can You write command-line with `execute=0`, so I can understand the situation better, .e.g, what cookie is passed, auth is to gateway or portal, etc.

**Comment by coldcoff** [comment]
That "argument via ..." message seems to be coming from your `vpnc-script`, probably when it runs `ip`.

You can check the `vpnc-script` version used in your setup and try to uncomment the `set -x` in there (in the upper part) to get a debug log about what it does:
![image](https://user-images.githubusercontent.com/14311781/83192400-c180be00-a135-11ea-85bd-70e04b650ddc.png)

**Comment by arthepsy** [comment]
@gunslingerfry any luck hunting this down?

**Comment by gunslingerfry** [comment]
Ok. Apologies for the delay. I hope I've properly obfuscated my personal data properly here. Attached is the log with debug turned on.
[log.txt](https://github.com/arthepsy/pan-globalprotect-okta/files/4788289/log.txt)

**Comment by gunslingerfry** [comment]
So this must be a problem with openconnect 8.05. I now have 8.10 and it's fine and I cannot get the logout unsuccessful message any longer. Closing the issue.
